-- PostgreSQL Schema for MeProject

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT 'User',
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  recoveryKey VARCHAR(255) NOT NULL,
  isDemo BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  dueDate DATE NOT NULL,
  cancelled BOOLEAN NOT NULL DEFAULT false,
  techStack JSONB NOT NULL,
  userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  projectId INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL,
  priority VARCHAR(50) NOT NULL,
  dueDate DATE NOT NULL,
  description TEXT NOT NULL,
  userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE NOT NULL,
  taskId INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS attachments (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  projectId INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  filePath TEXT NOT NULL,
  userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
